name: Coolify Auto-Update Check
on:
  schedule:
    - cron: '0 * * * *' # Chạy mỗi giờ một lần
  workflow_dispatch:      # Cho phép chạy tay

jobs:
  check-updates:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install regctl
        run: |
          curl -L -s https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 > regctl
          chmod +x regctl
          sudo mv regctl /usr/local/bin/

      - name: Run Update Script
        env:
          COOLIFY_TOKEN: ${{ secrets.COOLIFY_TOKEN }}
          COOLIFY_URL: ${{ secrets.COOLIFY_URL }}
          MY_CONFIG_PAT: ${{ secrets.MY_CONFIG_PAT }}
          CONFIG_URL: ${{ secrets.CONFIG_URL }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }} # Thêm dòng này
        run: bash check_and_deploy.sh

      - name: Commit & Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [[ -n $(git status --porcelain apps_state.json) ]]; then
            git add apps_state.json
            git commit -m "chore: update image digests [skip ci]"
            git pull --rebase origin main
            git push -q
          else
            echo "No updates to commit."
          fi
